version: '2'
services:
    samacvapp-app:
        image: samacvapp
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://samacvapp-mysql:3306/samacvapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 1717:1717
    samacvapp-mysql:
        extends:
            file: mysql.yml
            service: samacvapp-mysql
